-- Supabase Schema for Muskaan Electronics

-- Users Table
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT,
  role TEXT NOT NULL,
  status TEXT NOT NULL,
  "lastLogin" TEXT
);

-- Products Table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  brand TEXT NOT NULL,
  category TEXT NOT NULL,
  cost TEXT NOT NULL,
  selling TEXT NOT NULL,
  stock INTEGER NOT NULL,
  "minStock" INTEGER,
  status TEXT NOT NULL,
  image TEXT
);

-- Sales Table
CREATE TABLE sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  items JSONB NOT NULL,
  "totalAmount" NUMERIC NOT NULL,
  subtotal NUMERIC,
  discount NUMERIC,
  "paymentMethod" TEXT NOT NULL,
  date TEXT NOT NULL,
  "customerName" TEXT,
  notes TEXT
);

-- Quotes Table
CREATE TABLE quotes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  items JSONB NOT NULL,
  "totalAmount" NUMERIC NOT NULL,
  date TEXT NOT NULL,
  "customerName" TEXT,
  notes TEXT,
  status TEXT NOT NULL
);

-- Purchase Orders Table
CREATE TABLE "purchaseOrders" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  items JSONB NOT NULL,
  "totalAmount" NUMERIC NOT NULL,
  "supplierName" TEXT NOT NULL,
  date TEXT NOT NULL,
  "expectedDeliveryDate" TEXT,
  status TEXT NOT NULL,
  notes TEXT,
  "rejectionReason" TEXT
);

-- Deliveries Table
CREATE TABLE deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "purchaseOrderId" BIGINT,
  "lpoNumber" TEXT,
  items JSONB NOT NULL,
  "supplierName" TEXT NOT NULL,
  date TEXT NOT NULL,
  "receivedBy" TEXT NOT NULL,
  notes TEXT
);

-- Returns Table
CREATE TABLE returns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "saleId" BIGINT,
  "originalSaleId" BIGINT,
  items JSONB NOT NULL,
  "totalRefund" NUMERIC NOT NULL,
  "customerName" TEXT NOT NULL,
  date TEXT NOT NULL,
  reason TEXT NOT NULL,
  condition TEXT NOT NULL
);

-- Stock History Table
CREATE TABLE "stockHistory" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "productId" BIGINT NOT NULL,
  "changeType" TEXT NOT NULL,
  "quantityChange" INTEGER NOT NULL,
  "previousStock" INTEGER NOT NULL,
  "newStock" INTEGER NOT NULL,
  date TEXT NOT NULL,
  reason TEXT,
  "userId" BIGINT
);

-- Messages Table
CREATE TABLE messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "senderId" BIGINT NOT NULL,
  "senderName" TEXT NOT NULL,
  "senderRole" TEXT NOT NULL,
  "receiverId" TEXT NOT NULL, -- can be number or string like 'all_managers'
  subject TEXT NOT NULL,
  content TEXT NOT NULL,
  date TEXT NOT NULL,
  read BOOLEAN NOT NULL DEFAULT FALSE,
  type TEXT NOT NULL
);

-- Insert initial data
INSERT INTO users (name, email, password, role, status, "lastLogin") VALUES
('Admin User', 'admin@muskaan.com', 'admin123', 'Super Admin', 'Active', 'Just now'),
('Rahul Sharma', 'rahul@muskaan.com', 'password123', 'Manager', 'Active', '2 hours ago'),
('Priya Mehta', 'priya@muskaan.com', 'password123', 'Cashier', 'Active', 'Yesterday'),
('Amit Kumar', 'amit@muskaan.com', 'password123', 'Cashier', 'Inactive', '5 days ago');

INSERT INTO products (name, brand, category, cost, selling, stock, status, image) VALUES
('iPhone 15 Pro Max', 'Apple', 'Smartphones', 'Ksh 999.00', 'Ksh 1,199.00', 45, 'In Stock', 'https://picsum.photos/seed/iphone/200'),
('Samsung QN90C Neo QLED', 'Samsung', 'Televisions', 'Ksh 1,200.00', 'Ksh 1,599.00', 8, 'Low Stock', 'https://picsum.photos/seed/tv/200'),
('Sony WH-1000XM5', 'Sony', 'Audio', 'Ksh 250.00', 'Ksh 349.99', 0, 'Out of Stock', 'https://picsum.photos/seed/headphones/200'),
('MacBook Air M3 15"', 'Apple', 'Laptops', 'Ksh 1,050.00', 'Ksh 1,299.00', 22, 'In Stock', 'https://picsum.photos/seed/macbook/200'),
('Dell XPS 13', 'Dell', 'Laptops', 'Ksh 850.00', 'Ksh 999.00', 5, 'Low Stock', 'https://picsum.photos/seed/dell/200');
